spring:
  application:
    name: reviewX
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://211.48.114.37:3306/reviewx?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: cmcm
    password: cm1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update  # 프로덕션에서는 validate 사용
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        
  # Thymeleaf Configuration
  thymeleaf:
    cache: false  # 개발 환경에서 캐시 비활성화
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      
  # Security Configuration (OAuth2 - 추후 설정)
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: ${KAKAO_REDIRECT_URI:http://localhost:8080/login/oauth2/code/kakao}
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Custom Application Configuration
app:
  file:
    upload-dir: ./uploads
  image:
    max-size: 5242880  # 5MB
    allowed-types: jpg,jpeg,png
  payment:
    pg-type: ${PG_TYPE:test}  # test, toss, inicis 등
  
# Logging Configuration
logging:
  level:
    com.reviewx: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/reviewx.log